// web/lib/services/metadata-sync.ts
import 'dotenv/config'
import { ethers } from 'ethers'
import { INFT_ABI } from '@/lib/contracts/abis'
import { uploadToStorage } from '@/lib/storage/client-server'
import fs from 'fs/promises'
import path from 'path'
import crypto from 'crypto'

function normalizeHash(input: string): string {
  if (!input) return ''
  let h = input.trim()

  for (const pref of ['local://', 'file://']) {
    if (h.startsWith(pref)) h = h.slice(pref.length)
  }

  // Если это turbo-URL — взять хвост после последнего слэша
  if (h.startsWith('http')) {
    try {
      const u = new URL(h)
      const last = u.pathname.split('/').filter(Boolean).pop()
      if (last) h = last
    } catch {/* ignore */}
  }

  // базовая валидация 0x + 64 hex
  if (!/^0x[0-9a-fA-F]{64}$/.test(h)) return ''
  return h.toLowerCase()
}

export class MetadataSyncService {
  private static instance: MetadataSyncService
  private syncInterval: NodeJS.Timeout | null = null
  private isSyncing = false
  
  static getInstance() {
    if (!this.instance) {
      this.instance = new MetadataSyncService()
    }
    return this.instance
  }
  
  async syncMissingMetadata() {
    if (this.isSyncing) return
    this.isSyncing = true
    
    console.log('[MetadataSync] Starting sync...')
    
    try {
      const provider = new ethers.JsonRpcProvider(process.env.NEXT_PUBLIC_0G_RPC_URL)
      const contract = new ethers.Contract(
        process.env.NEXT_PUBLIC_INFT_CONTRACT_ADDRESS!,
        INFT_ABI,
        provider
      )
      
      const totalSupply = await contract.totalSupply()
      const metadataDir = path.join(process.cwd(), 'data', 'metadata')
      await fs.mkdir(metadataDir, { recursive: true })
      
      let fixedCount = 0
      
      for (let i = 0; i < Number(totalSupply); i++) {
        try {
          const tokenId = await contract.tokenByIndex(i)
          let metadataHash = await contract.getEncryptedURI(tokenId)
          
          // Normalize hash using the new function
          let cleanHash = normalizeHash(metadataHash)
          
          if (!cleanHash) {
            console.log(`[MetadataSync] Skipping invalid hash for token #${tokenId}: ${metadataHash}`)
            continue
          }
          
          // Проверяем существует ли файл локально
          const filePath = path.join(metadataDir, `${cleanHash}.json`)
          try {
            await fs.access(filePath)
            console.log(`[MetadataSync] Token #${tokenId} already has local metadata`)
            continue // Файл существует
          } catch {
            // Файл не существует, пробуем загрузить
          }
          
          // Пробуем загрузить из 0G Storage
          try {
            const response = await fetch(`${process.env.NEXT_PUBLIC_0G_STORAGE_URL}/api/v0/file/download`, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ 
                root: cleanHash.replace('0x', '') // 0G Storage может не любить префикс
              })
            })
            
            if (response.ok) {
              const content = await response.text()
              await fs.writeFile(filePath, content)
              console.log(`[MetadataSync] Downloaded metadata for token #${tokenId}`)
              fixedCount++
            } else {
              throw new Error('Download failed')
            }
          } catch (downloadError) {
            console.error(`[MetadataSync] Failed to download metadata for token #${tokenId}:`, downloadError)
            
            // Создаем fallback метаданные
            const metadata = {
              name: `AI Agent #${tokenId}`,
              description: 'Intelligent AI assistant powered by advanced language models',
              model: Number(tokenId) % 2 === 0 ? 'deepseek-r1-70b' : 'llama-3.3-70b',
              personality: ['friendly', 'professional', 'creative', 'analytical', 'mentor'][Number(tokenId) % 5],
              systemPrompt: `You are AI Agent #${tokenId}, an intelligent assistant.`,
              skills: ['conversation', 'analysis', 'creative writing'],
              image: `https://api.dicebear.com/7.x/bottts/svg?seed=agent-${tokenId}`,
              createdAt: new Date().toISOString(),
              tokenId: tokenId.toString(),
              autoGenerated: true,
              error: 'original_metadata_not_found'
            }
            
            await fs.writeFile(filePath, JSON.stringify(metadata, null, 2))
            console.log(`[MetadataSync] Created fallback for token #${tokenId}`)
            fixedCount++
          }
        } catch (error) {
          console.error(`[MetadataSync] Error processing token ${i}:`, error)
        }
      }
      
      console.log(`[MetadataSync] Sync completed. Fixed ${fixedCount} tokens`)
      
    } catch (error) {
      console.error('[MetadataSync] Sync error:', error)
    } finally {
      this.isSyncing = false
    }
  }
  
  startAutoSync(intervalMinutes = 5) {
    if (this.syncInterval) {
      clearInterval(this.syncInterval)
    }

    // Первый запуск сразу
    this.syncMissingMetadata()
    this.retryFailedUploads().catch(console.error)

    // Затем каждые N минут
    this.syncInterval = setInterval(() => {
      this.syncMissingMetadata()
    }, intervalMinutes * 60 * 1000)

    setInterval(() => {
      this.retryFailedUploads().catch(console.error)
    }, 30 * 60 * 1000)
    
    console.log(`[MetadataSync] Auto-sync started (every ${intervalMinutes} minutes)`)
  }
  
  stopAutoSync() {
    if (this.syncInterval) {
      clearInterval(this.syncInterval)
      this.syncInterval = null
      console.log('[MetadataSync] Auto-sync stopped')
    }
  }

  async retryFailedUploads() {
    const provider = new ethers.JsonRpcProvider(process.env.NEXT_PUBLIC_0G_RPC_URL)
    const wallet = new ethers.Wallet(process.env.OG_STORAGE_PRIVATE_KEY!, provider)
    const contract = new ethers.Contract(process.env.NEXT_PUBLIC_INFT_CONTRACT_ADDRESS!, INFT_ABI, wallet)
    const total = await contract.totalSupply()
    for (let i = 0; i < Number(total); i++) {
      const tokenId = await contract.tokenByIndex(i)
      const uri: string = await contract.getEncryptedURI(tokenId)
      
      // Use normalizeHash to check if this needs retry
      const normalizedHash = normalizeHash(uri)
      if (!normalizedHash && (uri.startsWith('local://') || uri.startsWith('file://'))) {
        const hash = uri.replace(/^(local:\/\/|file:\/\/)/, '')
        const filePath = path.join(process.cwd(), 'data', 'metadata', `${hash}.json`)
        try {
          const content = await fs.readFile(filePath, 'utf-8')
          const { rootHash } = await uploadToStorage(content, `${hash}.json`)
          if (!rootHash.startsWith('local://')) {
            // Assume contract has setTokenURI or similar method
            try {
              await (contract as any).setTokenURI(tokenId, rootHash)
            } catch {}
          }
        } catch (e) {
          console.error('[MetadataSync] Retry upload failed:', e)
        }
      }
    }
  }

}
