// web/lib/services/metadata-sync.ts
import 'dotenv/config'
import { ethers } from 'ethers'
import { INFT_ABI } from '@/lib/contracts/abis'
import fs from 'fs/promises'
import path from 'path'
import crypto from 'crypto'

export class MetadataSyncService {
  private static instance: MetadataSyncService
  private syncInterval: NodeJS.Timeout | null = null
  private isSyncing = false
  
  static getInstance() {
    if (!this.instance) {
      this.instance = new MetadataSyncService()
    }
    return this.instance
  }
  
  async syncMissingMetadata() {
    if (this.isSyncing) return
    this.isSyncing = true
    
    console.log('[MetadataSync] Starting sync...')
    
    try {
      const provider = new ethers.JsonRpcProvider(process.env.NEXT_PUBLIC_0G_RPC_URL)
      const contract = new ethers.Contract(
        process.env.NEXT_PUBLIC_INFT_CONTRACT_ADDRESS!,
        INFT_ABI,
        provider
      )
      
      const totalSupply = await contract.totalSupply()
      const metadataDir = path.join(process.cwd(), 'data', 'metadata')
      await fs.mkdir(metadataDir, { recursive: true })
      
      let fixedCount = 0
      
      for (let i = 0; i < Number(totalSupply); i++) {
        try {
          const tokenId = await contract.tokenByIndex(i)
          let metadataHash = await contract.getEncryptedURI(tokenId)
          
          // Очищаем хэш от URL если он есть
          let cleanHash = metadataHash
          if (metadataHash && typeof metadataHash === 'string') {
            if (metadataHash.includes('http://') || metadataHash.includes('https://')) {
              console.warn(`Token #${tokenId} has URL instead of hash:`, metadataHash)
              const parts = metadataHash.split('/')
              cleanHash = parts[parts.length - 1]
              console.log('Extracted hash:', cleanHash)
            }
            
            // Добавляем префикс 0x если нужно
            if (cleanHash && !cleanHash.startsWith('0x')) {
              if (/^[a-fA-F0-9]{64}$/.test(cleanHash)) {
                cleanHash = '0x' + cleanHash
              }
            }
          }
          
          // Проверяем существует ли файл локально
          const filePath = path.join(metadataDir, `${cleanHash}.json`)
          try {
            await fs.access(filePath)
            console.log(`[MetadataSync] Token #${tokenId} already has local metadata`)
            continue // Файл существует
          } catch {
            // Файл не существует, пробуем загрузить
          }
          
          // Пробуем загрузить из 0G Storage
          try {
            const response = await fetch(`${process.env.NEXT_PUBLIC_0G_STORAGE_URL}/api/v0/file/download`, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ 
                root: cleanHash.replace('0x', '') // 0G Storage может не любить префикс
              })
            })
            
            if (response.ok) {
              const content = await response.text()
              await fs.writeFile(filePath, content)
              console.log(`[MetadataSync] Downloaded metadata for token #${tokenId}`)
              fixedCount++
            } else {
              throw new Error('Download failed')
            }
          } catch (downloadError) {
            console.error(`[MetadataSync] Failed to download metadata for token #${tokenId}:`, downloadError)
            
            // Создаем fallback метаданные
            const metadata = {
              name: `AI Agent #${tokenId}`,
              description: 'Intelligent AI assistant powered by advanced language models',
              model: Number(tokenId) % 2 === 0 ? 'deepseek-r1-70b' : 'llama-3.3-70b',
              personality: ['friendly', 'professional', 'creative', 'analytical', 'mentor'][Number(tokenId) % 5],
              systemPrompt: `You are AI Agent #${tokenId}, an intelligent assistant.`,
              skills: ['conversation', 'analysis', 'creative writing'],
              image: `https://api.dicebear.com/7.x/bottts/svg?seed=agent-${tokenId}`,
              createdAt: new Date().toISOString(),
              tokenId: tokenId.toString(),
              autoGenerated: true,
              error: 'original_metadata_not_found'
            }
            
            await fs.writeFile(filePath, JSON.stringify(metadata, null, 2))
            console.log(`[MetadataSync] Created fallback for token #${tokenId}`)
            fixedCount++
          }
        } catch (error) {
          console.error(`[MetadataSync] Error processing token ${i}:`, error)
        }
      }
      
      console.log(`[MetadataSync] Sync completed. Fixed ${fixedCount} tokens`)
      
    } catch (error) {
      console.error('[MetadataSync] Sync error:', error)
    } finally {
      this.isSyncing = false
    }
  }
  
  startAutoSync(intervalMinutes = 5) {
    if (this.syncInterval) {
      clearInterval(this.syncInterval)
    }
    
    // Первый запуск сразу
    this.syncMissingMetadata()
    
    // Затем каждые N минут
    this.syncInterval = setInterval(() => {
      this.syncMissingMetadata()
    }, intervalMinutes * 60 * 1000)
    
    console.log(`[MetadataSync] Auto-sync started (every ${intervalMinutes} minutes)`)
  }
  
  stopAutoSync() {
    if (this.syncInterval) {
      clearInterval(this.syncInterval)
      this.syncInterval = null
      console.log('[MetadataSync] Auto-sync stopped')
    }
  }

}
