// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// PrivateKey private key
//
// swagger:model privateKey
type PrivateKey []string

// Validate validates this private key
func (m PrivateKey) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this private key based on context it is used
func (m PrivateKey) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
