/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InferenceServing } from './InferenceServing.js'
export * as factories from './factories/index.js'
export { InferenceServing__factory } from './factories/InferenceServing__factory.js'
