// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCheckSignatureParams creates a new CheckSignatureParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCheckSignatureParams() *CheckSignatureParams {
	return &CheckSignatureParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCheckSignatureParamsWithTimeout creates a new CheckSignatureParams object
// with the ability to set a timeout on a request.
func NewCheckSignatureParamsWithTimeout(timeout time.Duration) *CheckSignatureParams {
	return &CheckSignatureParams{
		timeout: timeout,
	}
}

// NewCheckSignatureParamsWithContext creates a new CheckSignatureParams object
// with the ability to set a context for a request.
func NewCheckSignatureParamsWithContext(ctx context.Context) *CheckSignatureParams {
	return &CheckSignatureParams{
		Context: ctx,
	}
}

// NewCheckSignatureParamsWithHTTPClient creates a new CheckSignatureParams object
// with the ability to set a custom HTTPClient for a request.
func NewCheckSignatureParamsWithHTTPClient(client *http.Client) *CheckSignatureParams {
	return &CheckSignatureParams{
		HTTPClient: client,
	}
}

/*
CheckSignatureParams contains all the parameters to send to the API endpoint

	for the check signature operation.

	Typically these are written to a http.Request.
*/
type CheckSignatureParams struct {

	// Body.
	Body CheckSignatureBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the check signature params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CheckSignatureParams) WithDefaults() *CheckSignatureParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the check signature params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CheckSignatureParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the check signature params
func (o *CheckSignatureParams) WithTimeout(timeout time.Duration) *CheckSignatureParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check signature params
func (o *CheckSignatureParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check signature params
func (o *CheckSignatureParams) WithContext(ctx context.Context) *CheckSignatureParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check signature params
func (o *CheckSignatureParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check signature params
func (o *CheckSignatureParams) WithHTTPClient(client *http.Client) *CheckSignatureParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check signature params
func (o *CheckSignatureParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the check signature params
func (o *CheckSignatureParams) WithBody(body CheckSignatureBody) *CheckSignatureParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the check signature params
func (o *CheckSignatureParams) SetBody(body CheckSignatureBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CheckSignatureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
