// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSignatureParams creates a new SignatureParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSignatureParams() *SignatureParams {
	return &SignatureParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSignatureParamsWithTimeout creates a new SignatureParams object
// with the ability to set a timeout on a request.
func NewSignatureParamsWithTimeout(timeout time.Duration) *SignatureParams {
	return &SignatureParams{
		timeout: timeout,
	}
}

// NewSignatureParamsWithContext creates a new SignatureParams object
// with the ability to set a context for a request.
func NewSignatureParamsWithContext(ctx context.Context) *SignatureParams {
	return &SignatureParams{
		Context: ctx,
	}
}

// NewSignatureParamsWithHTTPClient creates a new SignatureParams object
// with the ability to set a custom HTTPClient for a request.
func NewSignatureParamsWithHTTPClient(client *http.Client) *SignatureParams {
	return &SignatureParams{
		HTTPClient: client,
	}
}

/*
SignatureParams contains all the parameters to send to the API endpoint

	for the signature operation.

	Typically these are written to a http.Request.
*/
type SignatureParams struct {

	// Body.
	Body SignatureBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the signature params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SignatureParams) WithDefaults() *SignatureParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the signature params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SignatureParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the signature params
func (o *SignatureParams) WithTimeout(timeout time.Duration) *SignatureParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the signature params
func (o *SignatureParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the signature params
func (o *SignatureParams) WithContext(ctx context.Context) *SignatureParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the signature params
func (o *SignatureParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the signature params
func (o *SignatureParams) WithHTTPClient(client *http.Client) *SignatureParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the signature params
func (o *SignatureParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the signature params
func (o *SignatureParams) WithBody(body SignatureBody) *SignatureParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the signature params
func (o *SignatureParams) SetBody(body SignatureBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SignatureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
