// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGenerateProofInputParams creates a new GenerateProofInputParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGenerateProofInputParams() *GenerateProofInputParams {
	return &GenerateProofInputParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGenerateProofInputParamsWithTimeout creates a new GenerateProofInputParams object
// with the ability to set a timeout on a request.
func NewGenerateProofInputParamsWithTimeout(timeout time.Duration) *GenerateProofInputParams {
	return &GenerateProofInputParams{
		timeout: timeout,
	}
}

// NewGenerateProofInputParamsWithContext creates a new GenerateProofInputParams object
// with the ability to set a context for a request.
func NewGenerateProofInputParamsWithContext(ctx context.Context) *GenerateProofInputParams {
	return &GenerateProofInputParams{
		Context: ctx,
	}
}

// NewGenerateProofInputParamsWithHTTPClient creates a new GenerateProofInputParams object
// with the ability to set a custom HTTPClient for a request.
func NewGenerateProofInputParamsWithHTTPClient(client *http.Client) *GenerateProofInputParams {
	return &GenerateProofInputParams{
		HTTPClient: client,
	}
}

/*
GenerateProofInputParams contains all the parameters to send to the API endpoint

	for the generate proof input operation.

	Typically these are written to a http.Request.
*/
type GenerateProofInputParams struct {

	// Body.
	Body GenerateProofInputBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the generate proof input params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateProofInputParams) WithDefaults() *GenerateProofInputParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the generate proof input params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateProofInputParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the generate proof input params
func (o *GenerateProofInputParams) WithTimeout(timeout time.Duration) *GenerateProofInputParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the generate proof input params
func (o *GenerateProofInputParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the generate proof input params
func (o *GenerateProofInputParams) WithContext(ctx context.Context) *GenerateProofInputParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the generate proof input params
func (o *GenerateProofInputParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the generate proof input params
func (o *GenerateProofInputParams) WithHTTPClient(client *http.Client) *GenerateProofInputParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the generate proof input params
func (o *GenerateProofInputParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the generate proof input params
func (o *GenerateProofInputParams) WithBody(body GenerateProofInputBody) *GenerateProofInputParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the generate proof input params
func (o *GenerateProofInputParams) SetBody(body GenerateProofInputBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GenerateProofInputParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
