'use client'

import React, { useState, useEffect, useCallback, useMemo } from 'react'
import { useAccount, usePublicClient } from 'wagmi'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'
import Link from 'next/link'
import { INFT_ABI } from '@/lib/contracts/abis'
import { 
  MessageCircle, 
  Brain, 
  Search,
  Filter,
  Bot,
  Sparkles,
  Clock,
  User,
  ArrowRight,
  Loader2
} from 'lucide-react'

interface Agent {
  tokenId: string
  metadata?: {
    name: string
    description: string
    model?: string
    personality?: string
    image?: string
    skills?: string[]
    autoGenerated?: boolean
  }
  status: 'owned' | 'listed' | 'available'
}

interface AgentCardProps {
  agent: Agent
  isLoading?: boolean
  enableSale?: boolean
  enableTransfer?: boolean
  enableClone?: boolean
}

const AgentCardSkeleton = () => (
  <Card className="p-6 bg-white/5 backdrop-blur-xl border border-white/10 hover-glow">
    <div className="space-y-4">
      <div className="flex items-center space-x-3">
        <Skeleton className="w-12 h-12 rounded-full bg-white/10" />
        <div className="flex-1 space-y-2">
          <Skeleton className="h-4 w-3/4 bg-white/10" />
          <Skeleton className="h-3 w-1/2 bg-white/10" />
        </div>
      </div>
      <Skeleton className="h-3 w-full bg-white/10" />
      <Skeleton className="h-3 w-4/5 bg-white/10" />
      <div className="flex space-x-2">
        <Skeleton className="h-8 w-16 bg-white/10" />
        <Skeleton className="h-8 w-20 bg-white/10" />
      </div>
    </div>
  </Card>
)

const AgentCard: React.FC<AgentCardProps> = ({ 
  agent, 
  isLoading, 
  enableSale = false, 
  enableTransfer = false, 
  enableClone = false 
}) => {
  if (isLoading) return <AgentCardSkeleton />

  const { metadata } = agent
  const defaultImage = `https://api.dicebear.com/7.x/bottts/svg?seed=agent-${agent.tokenId}`

  return (
    <Card className="group relative overflow-hidden bg-white/5 backdrop-blur-xl border border-white/10 hover:border-0g-500/50 transition-all duration-300 hover:-translate-y-1 hover:shadow-2xl hover:shadow-0g-500/25">
      {/* Gradient overlay on hover */}
      <div className="absolute inset-0 bg-gradient-to-br from-0g-600/0 to-purple-600/0 group-hover:from-0g-600/10 group-hover:to-purple-600/10 transition-all duration-300" />
      
      <div className="relative p-6 space-y-4">
        {/* Header */}
        <div className="flex items-start space-x-4">
          <div className="relative">
            <div className="w-12 h-12 rounded-full bg-gradient-to-br from-0g-500 to-purple-500 flex items-center justify-center overflow-hidden">
              {metadata?.image ? (
                <img 
                  src={metadata.image} 
                  alt={metadata.name}
                  className="w-full h-full object-cover"
                />
              ) : (
                <Bot className="w-6 h-6 text-white" />
              )}
            </div>
            {metadata?.autoGenerated && (
              <div className="absolute -top-1 -right-1 w-4 h-4 bg-yellow-500 rounded-full flex items-center justify-center">
                <Sparkles className="w-2 h-2 text-white" />
              </div>
            )}
          </div>
          
          <div className="flex-1 min-w-0">
            <h3 className="text-white font-semibold text-lg truncate group-hover:text-0g-200 transition-colors">
              {metadata?.name || `Agent #${agent.tokenId}`}
            </h3>
            <p className="text-0g-300 text-sm">#{agent.tokenId}</p>
          </div>
          
          <Badge 
            variant="outline" 
            className="border-0g-400/50 text-0g-300 bg-0g-500/20"
          >
            {agent.status}
          </Badge>
        </div>

        {/* Description */}
        <p className="text-gray-300 text-sm line-clamp-2 leading-relaxed">
          {metadata?.description || 'An intelligent AI assistant ready to help with various tasks.'}
        </p>

        {/* Model & Personality Tags */}
        <div className="flex flex-wrap gap-2">
          {metadata?.model && (
            <Badge className="bg-blue-500/20 text-blue-300 border-blue-400/30 text-xs">
              {metadata.model}
            </Badge>
          )}
          {metadata?.personality && (
            <Badge className="bg-purple-500/20 text-purple-300 border-purple-400/30 text-xs">
              {metadata.personality}
            </Badge>
          )}
          {metadata?.skills && metadata.skills.length > 0 && (
            <Badge className="bg-green-500/20 text-green-300 border-green-400/30 text-xs">
              +{metadata.skills.length} skills
            </Badge>
          )}
        </div>

        {/* Actions */}
        <div className="grid grid-cols-2 gap-3 pt-2">
          <Link href={`/agent/${agent.tokenId}/chat`}>
            <Button 
              className="w-full bg-gradient-to-r from-0g-600 to-purple-600 hover:from-0g-700 hover:to-purple-700 text-white border-0 group-hover:shadow-lg group-hover:shadow-0g-500/25 transition-all duration-300"
              size="sm"
            >
              <MessageCircle className="w-4 h-4 mr-2" />
              Chat
            </Button>
          </Link>
          
          <Link href={`/agents/${agent.tokenId}/fine-tune`}>
            <Button 
              variant="outline"
              className="w-full border-white/20 text-gray-300 hover:text-white hover:bg-white/10 hover:border-0g-400/50 transition-all duration-300"
              size="sm"
              disabled={process.env.NEXT_PUBLIC_ENABLE_FINE_TUNE !== 'true'}
              title={process.env.NEXT_PUBLIC_ENABLE_FINE_TUNE !== 'true' ? 'Coming soon' : 'Fine-tune this agent'}
            >
              <Brain className="w-4 h-4 mr-2" />
              Tune
            </Button>
          </Link>
        </div>

        {/* Additional action buttons (temporarily disabled) */}
        <div className="grid grid-cols-3 gap-2 mt-2">
          <Button
            variant="outline"
            size="sm"
            disabled={!enableSale}
            className="text-xs border-white/10 text-gray-400 hover:text-gray-300 disabled:opacity-50"
            title={!enableSale ? 'Sale feature coming soon' : 'List for sale'}
          >
            Sale
          </Button>
          
          <Button
            variant="outline"
            size="sm"
            disabled={!enableTransfer}
            className="text-xs border-white/10 text-gray-400 hover:text-gray-300 disabled:opacity-50"
            title={!enableTransfer ? 'Transfer feature coming soon' : 'Transfer agent'}
          >
            Transfer
          </Button>
          
          <Button
            variant="outline"
            size="sm"
            disabled={!enableClone}
            className="text-xs border-white/10 text-gray-400 hover:text-gray-300 disabled:opacity-50"
            title={!enableClone ? 'Clone feature coming soon' : 'Clone agent'}
          >
            Clone
          </Button>
        </div>
      </div>
    </Card>
  )
}

export default function AgentsPage() {
  const { address } = useAccount()
  
  const [agents, setAgents] = useState<Agent[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [searchTerm, setSearchTerm] = useState('')
  const [modelFilter, setModelFilter] = useState<string>('')
  
  // Feature flags from environment
  const enableSale = process.env.NEXT_PUBLIC_ENABLE_SALE === 'true'
  const enableTransfer = process.env.NEXT_PUBLIC_ENABLE_TRANSFER === 'true'
  const enableClone = process.env.NEXT_PUBLIC_ENABLE_CLONE === 'true'

  const loadAgents = useCallback(async () => {
    setLoading(true)
    setError(null)
    
    try {
      // Use new API format with owner parameter
      const params = new URLSearchParams({
        page: '1',
        size: '50' // Load more agents per page
      })
      
      if (address) {
        params.set('owner', address)
      }
      
      const response = await fetch(`/api/agents/list?${params}`, {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
      })

      if (response.ok) {
        const data = await response.json()
        console.log('Agents API response:', data)
        
        // Use new API format
        const agentsData = data.items || []
        
        // Transform the data to match our interface
        const transformedAgents: Agent[] = agentsData.map((agent: any) => ({
          tokenId: agent.id,
          metadata: {
            name: agent.name || `Agent #${agent.id}`,
            description: agent.description || 'AI Agent',
            image: agent.image || '/images/default-agent.png', // Provide default image
            model: agent.meta?.model || 'unknown',
            // Add some default metadata if missing
            personality: 'Helpful Assistant',
            skills: ['conversation', 'analysis'],
            autoGenerated: false
          },
          status: 'owned' as const // For now, assume all listed agents are owned
        }))
        
        setAgents(transformedAgents)
        console.log(`Loaded ${transformedAgents.length} agents`)
      } else {
        const errorData = await response.json()
        console.error('Failed to load agents:', errorData)
        setError(errorData.error || 'Failed to load agents')
        setAgents([]) // Set empty array on error
      }
    } catch (error: any) {
      console.error('Error loading agents:', error)
      setError(error.message || 'Network error occurred')
      setAgents([]) // Set empty array on error
    } finally {
      setLoading(false)
    }
  }, [address]) // Remove publicClient dependency since we're using direct API calls

  useEffect(() => {
    loadAgents()
  }, [loadAgents])

  // Filter agents based on search and model filter
  const filteredAgents = useMemo(() => {
    return agents.filter(agent => {
      const matchesSearch = !searchTerm || 
        agent.metadata?.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        agent.metadata?.description?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        agent.tokenId.includes(searchTerm)
      
      const matchesModel = !modelFilter || 
        agent.metadata?.model?.toLowerCase().includes(modelFilter.toLowerCase())
      
      return matchesSearch && matchesModel
    })
  }, [agents, searchTerm, modelFilter])

  // Get unique models for filter
  const availableModels = useMemo(() => {
    const models = new Set<string>()
    agents.forEach(agent => {
      if (agent.metadata?.model) {
        models.add(agent.metadata.model)
      }
    })
    return Array.from(models)
  }, [agents])

  return (
    <div className="min-h-screen bg-gradient-to-br from-0g-950 via-purple-950 to-indigo-950 relative overflow-hidden">
      {/* Animated background elements */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-0g-500/20 rounded-full mix-blend-multiply filter blur-xl animate-blob"></div>
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-purple-500/20 rounded-full mix-blend-multiply filter blur-xl animate-blob animation-delay-2000"></div>
        <div className="absolute top-40 left-40 w-80 h-80 bg-indigo-500/20 rounded-full mix-blend-multiply filter blur-xl animate-blob animation-delay-4000"></div>
      </div>

      {/* Header */}
      <header className="relative z-10 bg-black/20 backdrop-blur-xl border-b border-white/10">
        <div className="container mx-auto px-4 py-8">
          <div className="text-center mb-8">
            <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">
              AI <span className="bg-gradient-to-r from-0g-400 to-purple-400 bg-clip-text text-transparent">Agents</span>
            </h1>
            <p className="text-0g-200 text-lg max-w-2xl mx-auto">
              Discover and interact with intelligent AI agents powered by 0G Network
            </p>
          </div>

          {/* Search and Filters */}
          <div className="max-w-4xl mx-auto space-y-4">
            <div className="flex flex-col md:flex-row gap-4">
              <div className="flex-1 relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
                <Input
                  placeholder="Search agents by name, description, or ID..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-10 bg-white/10 backdrop-blur-sm border-white/20 text-white placeholder-white/50 focus:ring-2 focus:ring-0g-500 focus:border-transparent"
                />
              </div>
              
              <div className="flex space-x-2">
                <select
                  value={modelFilter}
                  onChange={(e) => setModelFilter(e.target.value)}
                  className="px-4 py-2 bg-white/10 backdrop-blur-sm border border-white/20 rounded-lg text-white focus:ring-2 focus:ring-0g-500 focus:border-transparent"
                >
                  <option value="">All Models</option>
                  {availableModels.map(model => (
                    <option key={model} value={model} className="bg-gray-900">
                      {model}
                    </option>
                  ))}
                </select>
                
                <Link href="/mint">
                  <Button className="bg-gradient-to-r from-0g-600 to-purple-600 hover:from-0g-700 hover:to-purple-700 text-white whitespace-nowrap">
                    Create Agent
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* Agents Grid */}
      <main className="relative z-10 container mx-auto px-4 py-8">
        {error ? (
          <div className="text-center py-16">
            <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-red-500/20 flex items-center justify-center">
              <Bot className="w-8 h-8 text-red-400" />
            </div>
            <h3 className="text-xl font-semibold text-white mb-2">
              Failed to load agents
            </h3>
            <p className="text-red-300 mb-6">
              {error}
            </p>
            <Button 
              onClick={loadAgents}
              className="bg-gradient-to-r from-0g-600 to-purple-600 hover:from-0g-700 hover:to-purple-700 text-white"
            >
              {loading ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Retrying...
                </>
              ) : (
                <>
                  Try Again
                  <ArrowRight className="w-4 h-4 ml-2" />
                </>
              )}
            </Button>
          </div>
        ) : loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {Array.from({ length: 8 }).map((_, i) => (
              <AgentCardSkeleton key={i} />
            ))}
          </div>
        ) : filteredAgents.length > 0 ? (
          <>
            <div className="flex items-center justify-between mb-6">
              <p className="text-0g-200">
                {filteredAgents.length} agent{filteredAgents.length !== 1 ? 's' : ''} found
                {searchTerm && ` for "${searchTerm}"`}
              </p>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
              {filteredAgents.map((agent) => (
                <AgentCard 
                  key={agent.tokenId} 
                  agent={agent}
                  enableSale={enableSale}
                  enableTransfer={enableTransfer}
                  enableClone={enableClone}
                />
              ))}
            </div>
          </>
        ) : (
          <div className="text-center py-16">
            <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-gradient-to-r from-0g-500 to-purple-500 flex items-center justify-center">
              <Bot className="w-8 h-8 text-white" />
            </div>
            <h3 className="text-xl font-semibold text-white mb-2">
              {searchTerm ? 'No agents found' : 'No agents yet'}
            </h3>
            <p className="text-0g-300 mb-6">
              {searchTerm 
                ? 'Try adjusting your search terms or filters'
                : 'Create your first AI agent to get started'
              }
            </p>
            <Link href="/mint">
              <Button className="bg-gradient-to-r from-0g-600 to-purple-600 hover:from-0g-700 hover:to-purple-700 text-white">
                Create Your First Agent
                <ArrowRight className="w-4 h-4 ml-2" />
              </Button>
            </Link>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="relative z-10 bg-black/20 backdrop-blur-xl border-t border-white/10 mt-16">
        <div className="container mx-auto px-4 py-8">
          <div className="text-center">
            <p className="text-0g-300 text-sm">
              Powered by <span className="text-0g-400 font-semibold">0G Network</span> • 
              Decentralized AI at Scale
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
}