/**
 * This is an autogenerated file. Do not edit this file manually.
 *
 * key_pair.ts gives private and public key for signing the requests 
 * in all test in the `Settle fees` section in serving.spec.ts.
 */

import { BigNumberish } from "ethers";

export const privateKey: [BigNumberish, BigNumberish] = [
    BigInt(`0xddc70a51e0626712d9ebae15e648c355`),
    BigInt(`0x27edacd6408877debf15869ba10df370`),
];

export const publicKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x102257bb447696da13e4ca1775321672`),
    BigInt(`0x203b29e5306701bef17e5af39d736740`),
];
