/**
 * This is an autogenerated file. Do not edit this file manually.
 *
 * key_pair.ts gives private and public key for signing the requests 
 * in all test in the `Settle fees` section in serving.spec.ts.
 */

import { BigNumberish } from "ethers";

export const privateKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x4036bfa074f6b78a698b4f45f29b3f80`),
    BigInt(`0x24e6c4169fdf9ce8886d6f1d025af6e1`),
];

export const publicKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x3b902641c3de516f8a1b7eb1e5982477`),
    BigInt(`0x9ac63cf7a511be172113a270e0ee0f33`),
];
