// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RequestResponse request response
//
// swagger:model requestResponse
type RequestResponse struct {

	// nonce
	Nonce string `json:"nonce,omitempty"`

	// provider address
	ProviderAddress string `json:"providerAddress,omitempty"`

	// req fee
	ReqFee string `json:"reqFee,omitempty"`

	// The hash of the request, generated the combination of nonce, userAddress and providerAddress
	RequestHash []int64 `json:"requestHash"`

	// res fee
	ResFee string `json:"resFee,omitempty"`

	// tee signer address
	TeeSignerAddress string `json:"teeSignerAddress,omitempty"`

	// user address
	UserAddress string `json:"userAddress,omitempty"`
}

// Validate validates this request response
func (m *RequestResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request response based on context it is used
func (m *RequestResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestResponse) UnmarshalBinary(b []byte) error {
	var res RequestResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
