// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Signatures signatures
//
// swagger:model signatures
type Signatures [][]int64

// Validate validates this signatures
func (m Signatures) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this signatures based on context it is used
func (m Signatures) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
