// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGenerateSignatureParams creates a new GenerateSignatureParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGenerateSignatureParams() *GenerateSignatureParams {
	return &GenerateSignatureParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGenerateSignatureParamsWithTimeout creates a new GenerateSignatureParams object
// with the ability to set a timeout on a request.
func NewGenerateSignatureParamsWithTimeout(timeout time.Duration) *GenerateSignatureParams {
	return &GenerateSignatureParams{
		timeout: timeout,
	}
}

// NewGenerateSignatureParamsWithContext creates a new GenerateSignatureParams object
// with the ability to set a context for a request.
func NewGenerateSignatureParamsWithContext(ctx context.Context) *GenerateSignatureParams {
	return &GenerateSignatureParams{
		Context: ctx,
	}
}

// NewGenerateSignatureParamsWithHTTPClient creates a new GenerateSignatureParams object
// with the ability to set a custom HTTPClient for a request.
func NewGenerateSignatureParamsWithHTTPClient(client *http.Client) *GenerateSignatureParams {
	return &GenerateSignatureParams{
		HTTPClient: client,
	}
}

/*
GenerateSignatureParams contains all the parameters to send to the API endpoint

	for the generate signature operation.

	Typically these are written to a http.Request.
*/
type GenerateSignatureParams struct {

	// Body.
	Body GenerateSignatureBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the generate signature params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateSignatureParams) WithDefaults() *GenerateSignatureParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the generate signature params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateSignatureParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the generate signature params
func (o *GenerateSignatureParams) WithTimeout(timeout time.Duration) *GenerateSignatureParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the generate signature params
func (o *GenerateSignatureParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the generate signature params
func (o *GenerateSignatureParams) WithContext(ctx context.Context) *GenerateSignatureParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the generate signature params
func (o *GenerateSignatureParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the generate signature params
func (o *GenerateSignatureParams) WithHTTPClient(client *http.Client) *GenerateSignatureParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the generate signature params
func (o *GenerateSignatureParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the generate signature params
func (o *GenerateSignatureParams) WithBody(body GenerateSignatureBody) *GenerateSignatureParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the generate signature params
func (o *GenerateSignatureParams) SetBody(body GenerateSignatureBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GenerateSignatureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
