// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGenerateKeyPairParams creates a new GenerateKeyPairParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGenerateKeyPairParams() *GenerateKeyPairParams {
	return &GenerateKeyPairParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGenerateKeyPairParamsWithTimeout creates a new GenerateKeyPairParams object
// with the ability to set a timeout on a request.
func NewGenerateKeyPairParamsWithTimeout(timeout time.Duration) *GenerateKeyPairParams {
	return &GenerateKeyPairParams{
		timeout: timeout,
	}
}

// NewGenerateKeyPairParamsWithContext creates a new GenerateKeyPairParams object
// with the ability to set a context for a request.
func NewGenerateKeyPairParamsWithContext(ctx context.Context) *GenerateKeyPairParams {
	return &GenerateKeyPairParams{
		Context: ctx,
	}
}

// NewGenerateKeyPairParamsWithHTTPClient creates a new GenerateKeyPairParams object
// with the ability to set a custom HTTPClient for a request.
func NewGenerateKeyPairParamsWithHTTPClient(client *http.Client) *GenerateKeyPairParams {
	return &GenerateKeyPairParams{
		HTTPClient: client,
	}
}

/*
GenerateKeyPairParams contains all the parameters to send to the API endpoint

	for the generate key pair operation.

	Typically these are written to a http.Request.
*/
type GenerateKeyPairParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the generate key pair params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateKeyPairParams) WithDefaults() *GenerateKeyPairParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the generate key pair params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateKeyPairParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the generate key pair params
func (o *GenerateKeyPairParams) WithTimeout(timeout time.Duration) *GenerateKeyPairParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the generate key pair params
func (o *GenerateKeyPairParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the generate key pair params
func (o *GenerateKeyPairParams) WithContext(ctx context.Context) *GenerateKeyPairParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the generate key pair params
func (o *GenerateKeyPairParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the generate key pair params
func (o *GenerateKeyPairParams) WithHTTPClient(client *http.Client) *GenerateKeyPairParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the generate key pair params
func (o *GenerateKeyPairParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GenerateKeyPairParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
